### ISSUE TITLE
Please provide a Dockerfile for Eclipser 2.0

### ISSUE THREAD

**Issue by vanhauser-thc** [SoftSec-KAIST/Eclipser#16]
So that Eclipser can be used easily on current Linux plus not needing to install all the dependencies required - could you please supply a Dockerfile for Eclipser 2.0?
Based on the fuzzbench builder.Dockerfile + runner.Dockerfile this should not be too much work?
(I would do it myself, but too much on my plate for afl++ at the moment ...)

**Comment by vanhauser-thc** [comment]
btw - combining afl++ with eclipser gives it a huge performance improvement, bypassing entropic and libfuzzer: https://www.fuzzbench.com/reports/experimental/2020-12-25/index.html

**Comment by jchoi2022** [comment]
I believe it's a good idea to keep the Dockerfile for the latest Eclipser in the pository. Please try this [Dockerfile](https://github.com/SoftSec-KAIST/Eclipser/blob/dev/Dockerfile) in 'dev' branch.

**Comment by jchoi2022** [comment]
The result of integrating Eclipser  with AFL++ is interesting. If I understood the code correctly, AFL++ was run without 'cmplog' feature (https://github.com/google/fuzzbench/blob/master/fuzzers/aflplusplus_eclipser/fuzzer.py#L51).

This indicates that AFL++'s 'cmplog' feature (inspired from REDQUEEN) and Eclipser's grey-box concolic testing have almost equivalent effectiveness in increasing coverage. This makes sense because Eclisper and REDQUEEN tried to address the same research problem.

And I think integrating Eclipser with AFL is still meaningful, because the difference between (Eclipser & AFL) and (AFL) directly shows how effectively Eclipser solved branches that AFL could not cover. So I think it would be the best to keep both (Eclipser & AFL) and (Eclipser & AFL++) in fuzzbench.

**Comment by vanhauser-thc** [comment]
> I believe it's a good idea to keep the Dockerfile for the latest Eclipser in the pository. Please try this [Dockerfile](https://github.com/SoftSec-KAIST/Eclipser/blob/dev/Dockerfile) in 'dev' branch.

it build fine, thank you!
I would recommend to add `ENV DOTNET_CLI_TELEMETRY_OPTOUT=1`

**Comment by vanhauser-thc** [comment]
> The result of integrating Eclipser with AFL++ is interesting. If I understood the code correctly, AFL++ was run without 'cmplog' feature (https://github.com/google/fuzzbench/blob/master/fuzzers/aflplusplus_eclipser/fuzzer.py#L51).

yes

> This indicates that AFL++'s 'cmplog' feature (inspired from REDQUEEN) and Eclipser's grey-box concolic testing have almost equivalent effectiveness in increasing coverage. This makes sense because Eclisper and REDQUEEN tried to address the same research problem.

I would not say so, because it is not really a fair comparison.
afl/afl++ and eclipser together use 2 CPU cores/threads, whereas aflplusplus (with cmplog) is using only one.
So a fair comparison would be running them aginst 2xafl or 2xafl++ (one with cmplog one without).

I did the 2xafl++ (one with cmplog, one without) vs afl++ + eclipser here: https://www.fuzzbench.com/reports/experimental/2020-12-26/
due to a bug in fuzzbench it only completed half of the benchmark time, but it shows that the mono+binary analysis is - unsurprisingly - at a larger disadvantage.

but IMHO this is fine. there is no "the best" fuzzer. because what eclipser does has difference to cmplog it will usualyl find different paths, and that helps in a fuzzing campaign. plus it is easier to deploy than symcc, plus it also works on binary-only fuzzing.

maybe the best comparison would be to run aflplusplus_qemu with cmplog + aflplusplus_qemu without cmplog  vs   aflplusplus_qemu without cmplog + eclipser.

> And I think integrating Eclipser with AFL is still meaningful, because the difference between (Eclipser & AFL) and (AFL) directly shows how effectively Eclipser solved branches that AFL could not cover. So I think it would be the best to keep both (Eclipser & AFL) and (Eclipser & AFL++) in fuzzbench.

I don't mind, I was just curious how that would affect the ranking :)
will you take over the aflplusplus_eclipser maintainance for potential upcoming eclipser changes? I could handle any afl++ changes. and do you want it as a core fuzzer?

**Comment by jchoi2022** [comment]
I was assuming that each docker container used for fuzzing was confined to run with a single CPU core. If that was not the case, then I agree the comparison is unfair.

Actually, things get complicated here, because (Eclipser & AFL) will not fully utilize two cores even if if there are enough cores.
Since Eclipser was originally intended for a single-core environment, it monitors how effectively it increases coverage, and adaptively yields resource (i.e. sleeps) to give more resource to random fuzzing module (which is AFL in Eclipser v2.0). 

In my experience, the Eclipser thread will converge to utilize around 0.25 CPU cores eventually, when fuzzing time is long enough. This makes it hard to design a properly aligned comparison setting. Limiting the docker container to run with a single CPU core seems to be the best option so far.

**Comment by jchoi2022** [comment]
And yes, I can maintain aflplusplus_eclipser for future updates in Eclipser.

Although the result is promising, I would prefer not to include aflplusplus_eclipser in the core fuzzer. Since 'AFL++ without cmplog' is not included in the core fuzzer, it may be hard to see how much coverage improvement Eclipser gives over the random fuzzing baseline.

**Comment by vanhauser-thc** [comment]
I think this can be closed now. thanks!
