### ISSUE TITLE
Solving timeout

### ISSUE THREAD

**Issue by vanhauser-thc** [SoftSec-KAIST/Eclipser#19]
I am currently running a running a comparison on concolic solvers on fuzzbench:
https://www.fuzzbench.com/reports/experimental/2021-07-03-symbolic/index.html

Everything is set up as comparable as possible, however one important item is how long the solver is tying to solve until it is aborting.
Is this configurable in Eclipser? If yes - how? If not - what is the hard set value?

**Comment by jchoi2022** [comment]
Sorry for the late reply, I was too busy for the last few weeks.

Eclipser only targets linear and monotonic branches, and relies on its own simplified solver, not a full-fledged SMT solver.  And the simplified solver does not have a timeout configuration, because we assume that the targeted branches can be solved (or concluded to be not solvable) rather quickly.

Therefore, I think you don't have to consider timeout configuration of Eclipser.

**Comment by vanhauser-thc** [comment]
ok, thank you!
